name: Extract ZIP file

on:
  push:
    paths:
      - mapview.zip

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip file
        run: |
          mkdir -p mapview
          unzip mapview.zip -d mapview

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mapview
          git commit -m "Extract mapview.zip" || echo "No changes to commit"
          git push
